fix: make sure node is drained before rebooting when rebootDelay is g…
kubereboot/kured pull request #930
Opened 2024-05-08 15:18 UTC by sebastiangaiser

…reater than 0

closes #929

2024-05-08 19:25 UTC, jackfrancis commented
I've added some concerns in the original issue #929. Let's definitely figure out how to solve for this scenario, but I'm not sure that a second drain operation after the retry wait is the right solution.

2024-05-13 11:50 UTC, evrardjp requested changes
I don't think it's wise to add this _as is_. Let's discuss on the issue first maybe?

2024-05-13 11:50 UTC, evrardjp commented on cmd/kured/main.go
> +
I don't think it make sense to add this conditionally on reboot delay.

2024-05-13 11:50 UTC, evrardjp commented on cmd/kured/main.go
> +			err = drain(client, node)
I don' think we should trigger another drain. 

The state should be as _expected_ before reboot, but not triggering an extra drain. See @jackfrancis 's opinion on the issue.

2024-05-18 10:14 UTC, evrardjp commented
I like the idea, but I think we have details to iron out.

2024-07-18 06:23 UTC, sebastiangaiser commented
Not stale...

2024-08-07 14:25 UTC, evrardjp commented
@sebastiangaiser  maybe we could have a meeting and you explain your point of view/what's missing to progress this? I like the concept.

2024-08-08 17:43 UTC, sebastiangaiser commented
I'm sorry but I don't have the time, currently. Feel free to hijack/supersede my PR.

2024-10-29 02:01 UTC, closed without merging